[package]
name = "migrate_discord_db"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = { version = "1.0", features = ["derive"] }
csv = "1.1"
mongodb = "2.8.1"
tokio = { version = "1.36.0", features = ["full"] }
